"""SQLAlchemy models grouped by domain."""
from backend.bd.database import Base
from .core import (
    GENDER_ENUM,
    hash_iiko_password_sha1,
    user_restaurants,
    Company,
    Role,
    Permission,
    PositionPermission,
    RolePermission,
    UserPermission,
    User,
    UserThemePreference,
    AuthSession,
    Restaurant,
)
from .hr import PaymentFormat, Position, Attendance, PAYMENT_CALCULATION_MODE, RestaurantSubdivision
from .payroll import (
    PAYROLL_ADJUSTMENT_KIND,
    PAYROLL_ADVANCE_STATUS,
    PAYROLL_STATEMENT_KIND,
    PayrollAdjustmentType,
    PayrollAdjustment,
    PayrollSalaryResult,
    PayrollAdvanceStatement,
    PayrollAdvanceItem,
    PayrollAdvanceConsolidatedStatement,
    LaborSummarySettings,
)
from .training import TrainingEventType, TrainingEventRecord, PositionTrainingRequirement
from .inventory import (
    InvGroup,
    InvCategory,
    InvKind,
    InvItem,
    InvItemRecord,
    InvItemStock,
    InvItemChange,
    InvItemInstance,
    InvItemInstanceEvent,
    InvInstanceEventType,
    InvStoragePlace,
    InvMovementEvent,
)
from .medical import MedicalCheckStatus, MedicalCheckType, MedicalCheckRecord
from .checklists import (
    position_checklist_access,
    Checklist,
    ChecklistSection,
    ChecklistQuestion,
    ChecklistAnswer,
    ChecklistQuestionAnswer,
    ChecklistDraft,
    ChecklistDraftAnswer,
)
from .cis_documents import (
    CisDocumentStatus,
    CisDocumentType,
    CisDocumentRecord,
)
from .employment_documents import EmploymentDocumentKind, EmploymentDocumentRecord
from .kpi import (
    KPI_CALCULATION_BASE,
    KPI_THRESHOLD_TYPE,
    KPI_EFFECT_TYPE,
    KPI_VALUE_BASE,
    KPI_RESULT_STATUS,
    KPI_RESULT_SOURCE,
    KPI_COMPARISON_OPERATOR,
    KPI_RULE_COMPARISON_BASIS,
    KPI_PAYOUT_STATUS,
    KpiMetricGroup,
    KpiMetricGroupRule,
    KpiMetric,
    KpiRule,
    KpiResult,
    KpiPlanFact,
    KpiPlanPreference,
    KpiMetricGroupPlanFact,
    KpiMetricGroupPlanPreference,
    KpiPayoutBatch,
    KpiPayoutItem,
)
from .fingerprint import FingerprintEvent
from .employee_changes import EmployeeChangeEvent
from .employee_change_orders import EmployeeChangeOrder, EMPLOYEE_CHANGE_ORDER_STATUS
from .position_change_orders import PositionChangeOrder, POSITION_CHANGE_ORDER_STATUS
from .accounting import (
    AccountingInvoice,
    AccountingInvoiceClosingDocument,
    AccountingInvoiceChange,
    AccountingInvoiceEvent,
    AccountingCounterparty,
)
from .knowledge_base import (
    KNOWLEDGE_BASE_DOCUMENT_TYPE,
    KNOWLEDGE_BASE_AUDIT_ENTITY_TYPE,
    KNOWLEDGE_BASE_ACCESS_SCOPE_TYPE,
    KnowledgeBaseFolder,
    KnowledgeBaseDocument,
    KnowledgeBaseDocumentVersion,
    KnowledgeBaseAuditLog,
    KnowledgeBaseFolderAccessRule,
)

__all__ = ["Base", 
    "GENDER_ENUM",
    "hash_iiko_password_sha1",
    "user_restaurants",
    "Company",
    "Role",
    "Permission",
    "PositionPermission",
    "RolePermission",
    "UserPermission",
    "User",
    "UserThemePreference",
    "AuthSession",
    "Restaurant",
    "PAYMENT_CALCULATION_MODE",
    "PaymentFormat",
    "RestaurantSubdivision",
    "Position",
    "Attendance",
    "PAYROLL_ADJUSTMENT_KIND",
    "PAYROLL_ADVANCE_STATUS",
    "PAYROLL_STATEMENT_KIND",
    "PayrollAdjustmentType",
    "PayrollAdjustment",
    "PayrollSalaryResult",
    "PayrollAdvanceStatement",
    "PayrollAdvanceItem",
    "PayrollAdvanceConsolidatedStatement",
    "LaborSummarySettings",
    "TrainingEventType",
    "TrainingEventRecord",
    "InvGroup",
    "InvCategory",
    "InvKind",
    "InvItem",
    "InvItemRecord",
    "InvItemStock",
    "InvItemChange",
    "InvItemInstance",
    "InvItemInstanceEvent",
    "InvInstanceEventType",
    "InvStoragePlace",
    "InvMovementEvent",
    "MedicalCheckStatus",
    "MedicalCheckType",
    "MedicalCheckRecord",
    "position_checklist_access",
    "Checklist",
    "ChecklistSection",
    "ChecklistQuestion",
    "ChecklistAnswer",
    "ChecklistQuestionAnswer",
    "ChecklistDraft",
    "ChecklistDraftAnswer",
    "CisDocumentStatus",
    "CisDocumentType",
    "CisDocumentRecord",
    "EmploymentDocumentKind",
    "EmploymentDocumentRecord",
    "KPI_CALCULATION_BASE",
    "KPI_THRESHOLD_TYPE",
    "KPI_EFFECT_TYPE",
    "KPI_VALUE_BASE",
    "KPI_RESULT_STATUS",
    "KPI_RESULT_SOURCE",
    "KPI_COMPARISON_OPERATOR",
    "KPI_RULE_COMPARISON_BASIS",
    "KPI_PAYOUT_STATUS",
    "KpiMetricGroup",
    "KpiMetricGroupRule",
    "KpiMetric",
    "KpiRule",
    "KpiResult",
    "KpiPlanFact",
    "KpiPlanPreference",
    "KpiMetricGroupPlanFact",
    "KpiMetricGroupPlanPreference",
    "KpiPayoutBatch",
    "KpiPayoutItem",
    "FingerprintEvent",
    "EmployeeChangeEvent",
    "EmployeeChangeOrder",
    "EMPLOYEE_CHANGE_ORDER_STATUS",
    "PositionChangeOrder",
    "POSITION_CHANGE_ORDER_STATUS",
    "AccountingInvoice",
    "AccountingInvoiceClosingDocument",
    "AccountingInvoiceChange",
    "AccountingInvoiceEvent",
    "AccountingCounterparty",
    "KNOWLEDGE_BASE_DOCUMENT_TYPE",
    "KNOWLEDGE_BASE_AUDIT_ENTITY_TYPE",
    "KNOWLEDGE_BASE_ACCESS_SCOPE_TYPE",
    "KnowledgeBaseFolder",
    "KnowledgeBaseDocument",
    "KnowledgeBaseDocumentVersion",
    "KnowledgeBaseAuditLog",
    "KnowledgeBaseFolderAccessRule",
]
