"""Init HR fields + payment_formats + employee_positions + attendances

Revision ID: 226746b2b459
Revises: 728c817c9e64
Create Date: 2025-09-23 15:25:15.165474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226746b2b459'
down_revision: Union[str, Sequence[str], None] = '728c817c9e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_format_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_format_id'], ['payment_formats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_employee_positions_payment_format_id', 'employee_positions', ['payment_format_id'], unique=False)
    op.create_index('ix_employee_positions_role_id', 'employee_positions', ['role_id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('night_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['employee_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_position_id'), 'attendances', ['position_id'], unique=False)
    op.create_index(op.f('ix_attendances_restaurant_id'), 'attendances', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_attendances_user_id'), 'attendances', ['user_id'], unique=False)
    op.add_column('users', sa.Column('position_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('fire_date', sa.Date(), nullable=True))
    # 1) добавить колонку с дефолтом false, чтобы прошли EXISTING rows
    op.add_column('users', sa.Column('fired', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # 2) (необязательно, но правильно) убрать дефолт после заполнения
    op.alter_column('users', 'fired', server_default=None)

    op.add_column('users', sa.Column('staff_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('photo_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_position_id'), 'users', ['position_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['staff_code'])
    op.create_foreign_key(None, 'users', 'employee_positions', ['position_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_position_id'), table_name='users')
    op.drop_column('users', 'photo_key')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'staff_code')
    op.drop_column('users', 'fired')
    op.drop_column('users', 'fire_date')
    op.drop_column('users', 'hire_date')
    op.drop_column('users', 'rate')
    op.drop_column('users', 'position_id')
    op.drop_index(op.f('ix_attendances_user_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_restaurant_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_position_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index('ix_employee_positions_role_id', table_name='employee_positions')
    op.drop_index('ix_employee_positions_payment_format_id', table_name='employee_positions')
    op.drop_table('employee_positions')
    op.drop_table('payment_formats')
    # ### end Alembic commands ###
