"""Init HR fields + payment_formats + employee_positions + attendances

Revision ID: 5f6d057fc463
Revises: 226746b2b459
Create Date: 2025-09-24 17:44:59.609883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6d057fc463'
down_revision: Union[str, Sequence[str], None] = '226746b2b459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_groups_name'), 'inv_groups', ['name'], unique=True)
    op.create_table('inv_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['inv_groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'group_id', name='uq_inv_categories_name_group')
    )
    op.create_index(op.f('ix_inv_categories_group_id'), 'inv_categories', ['group_id'], unique=False)
    op.create_table('inv_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inv_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['inv_groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category_id', name='uq_inv_items_name_category')
    )
    op.create_index(op.f('ix_inv_items_category_id'), 'inv_items', ['category_id'], unique=False)
    op.create_index('ix_inv_items_group_category', 'inv_items', ['group_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_inv_items_group_id'), 'inv_items', ['group_id'], unique=False)
    op.create_table('inv_item_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inv_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['inv_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_item_records_category_id'), 'inv_item_records', ['category_id'], unique=False)
    op.create_index(op.f('ix_inv_item_records_group_id'), 'inv_item_records', ['group_id'], unique=False)
    op.create_index(op.f('ix_inv_item_records_item_id'), 'inv_item_records', ['item_id'], unique=False)
    op.create_index('ix_inv_item_records_restaurant_created', 'inv_item_records', ['restaurant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inv_item_records_restaurant_id'), 'inv_item_records', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_inv_item_records_user_id'), 'inv_item_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inv_item_records_user_id'), table_name='inv_item_records')
    op.drop_index(op.f('ix_inv_item_records_restaurant_id'), table_name='inv_item_records')
    op.drop_index('ix_inv_item_records_restaurant_created', table_name='inv_item_records')
    op.drop_index(op.f('ix_inv_item_records_item_id'), table_name='inv_item_records')
    op.drop_index(op.f('ix_inv_item_records_group_id'), table_name='inv_item_records')
    op.drop_index(op.f('ix_inv_item_records_category_id'), table_name='inv_item_records')
    op.drop_table('inv_item_records')
    op.drop_index(op.f('ix_inv_items_group_id'), table_name='inv_items')
    op.drop_index('ix_inv_items_group_category', table_name='inv_items')
    op.drop_index(op.f('ix_inv_items_category_id'), table_name='inv_items')
    op.drop_table('inv_items')
    op.drop_index(op.f('ix_inv_categories_group_id'), table_name='inv_categories')
    op.drop_table('inv_categories')
    op.drop_index(op.f('ix_inv_groups_name'), table_name='inv_groups')
    op.drop_table('inv_groups')
    # ### end Alembic commands ###
