"""create iiko tables

Revision ID: 6cdaf42c807d
Revises: e9c32d6577aa
Create Date: 2025-07-27 01:56:08.057073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdaf42c807d'
down_revision: Union[str, Sequence[str], None] = 'e9c32d6577aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iiko_employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iiko_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iiko_attendances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('regular_minutes', sa.Integer(), nullable=True),
    sa.Column('regular_payment_sum', sa.Float(), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_payment_sum', sa.Float(), nullable=True),
    sa.Column('attendance_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['iiko_employees.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['iiko_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date_from', name='uq_employee_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iiko_attendances')
    op.drop_table('iiko_roles')
    op.drop_table('iiko_employees')
    # ### end Alembic commands ###
