"""add iiko_olap_rows and iiko_product_rows

Revision ID: 728c817c9e64
Revises: 6cdaf42c807d
Create Date: 2025-08-13 11:31:05.412194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '728c817c9e64'
down_revision: Union[str, Sequence[str], None] = '6cdaf42c807d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iiko_olap_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('dish_code', sa.String(), nullable=True),
    sa.Column('dish_full_name', sa.String(), nullable=True),
    sa.Column('dish_measure_unit', sa.String(), nullable=True),
    sa.Column('dish_group', sa.String(), nullable=True),
    sa.Column('cooking_place', sa.String(), nullable=True),
    sa.Column('non_cash_payment_type', sa.String(), nullable=True),
    sa.Column('pay_types', sa.String(), nullable=True),
    sa.Column('dish_amount_int', sa.Integer(), nullable=True),
    sa.Column('dish_sum_int', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount_sum', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iiko_olap_rows_dish_code'), 'iiko_olap_rows', ['dish_code'], unique=False)
    op.create_index(op.f('ix_iiko_olap_rows_open_date'), 'iiko_olap_rows', ['open_date'], unique=False)
    op.create_index('ix_iiko_olap_rows_rest_date', 'iiko_olap_rows', ['restaurant_id', 'open_date'], unique=False)
    op.create_index(op.f('ix_iiko_olap_rows_restaurant_id'), 'iiko_olap_rows', ['restaurant_id'], unique=False)
    op.create_table('iiko_product_rows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('num', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('product_group_type', sa.String(), nullable=True),
    sa.Column('cooking_place_type', sa.String(), nullable=True),
    sa.Column('main_unit', sa.String(), nullable=True),
    sa.Column('product_category', sa.String(), nullable=True),
    sa.Column('containers', sa.Text(), nullable=True),
    sa.Column('barcodes', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_xml', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iiko_product_rows_code'), 'iiko_product_rows', ['code'], unique=False)
    op.create_index('ix_iiko_product_rows_rest_code', 'iiko_product_rows', ['restaurant_id', 'code'], unique=False)
    op.create_index(op.f('ix_iiko_product_rows_restaurant_id'), 'iiko_product_rows', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iiko_product_rows_restaurant_id'), table_name='iiko_product_rows')
    op.drop_index('ix_iiko_product_rows_rest_code', table_name='iiko_product_rows')
    op.drop_index(op.f('ix_iiko_product_rows_code'), table_name='iiko_product_rows')
    op.drop_table('iiko_product_rows')
    op.drop_index(op.f('ix_iiko_olap_rows_restaurant_id'), table_name='iiko_olap_rows')
    op.drop_index('ix_iiko_olap_rows_rest_date', table_name='iiko_olap_rows')
    op.drop_index(op.f('ix_iiko_olap_rows_open_date'), table_name='iiko_olap_rows')
    op.drop_index(op.f('ix_iiko_olap_rows_dish_code'), table_name='iiko_olap_rows')
    op.drop_table('iiko_olap_rows')
    # ### end Alembic commands ###
