"""Добавлены поля iiko_login и iiko_password_sha1 в Restaurant

Revision ID: e9c32d6577aa
Revises: 037ee0dee1a2
Create Date: 2025-07-27 00:38:28.238357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c32d6577aa'
down_revision: Union[str, Sequence[str], None] = '037ee0dee1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('iiko_login', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('iiko_password_sha1', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'iiko_password_sha1')
    op.drop_column('restaurants', 'iiko_login')
    # ### end Alembic commands ###
